# Generated by Django 3.2.3 on 2021-06-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pulished_date',
            new_name='published_date',
        ),
    ]
